import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import Link from 'next/link';
import React, { useState } from "react";

export default function Home() {
  
  return (
    <div className={styles.container}>
      <Head>
        <title>1stop</title>
        <meta name="description" content="Generated by create next app v " />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to 1stop
        </h1>
        </main>

  <div className={styles.form}>
  <form>
    <div className={styles.signin}>
  <div className={styles.label}>
    <label>
      Email
      </label>
      <br />
      <input type="email" name="email" /> 
  </div>
  <div className={styles.label}>
    <label>
      Password
    </label><br />
      <input type="password" name="password" />
  </div><br />
  <div className={styles.loga}>
   <p className={styles.signin}> <Link href="/dashboard" >login</Link></p>
    
    </div><br />
    <div>
            <p>new user?</p>
           <p> create an account <p className={styles.signup}><Link href="/login" >signup</Link></p></p>
           
          
          </div>
          </div>
</form>
    </div>      
          

      
    </div>
  )
}
